---
- hosts: all
  become: yes

  tasks:
    - name: Ensure chrony (for time syncronitazion) is installed.
    yum:
      name: chrony
      state: present

    - name: Ensure chrony is runnig.
    service:
      name: chronyd
      state: started
      enabled: yes